name: Github JD-autosign

on:
    push:
        branches:
            - master
    workflow_dispatch: # 手动触发
    schedule:
        - cron: '5 16 * * *'
jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              with:
                ref: 'master'
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: npm install
              run: npm install
            - run: all.bat
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                JD_COOKIE_2: ${{ secrets.JD_COOKIE_2 }} 
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
